# Generated by Django 4.2.16 on 2024-10-22 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfile',
            name='status',
            field=models.CharField(default='PENDING', max_length=20),
        ),
    ]
