# Generated by Django 4.2.16 on 2024-10-22 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0003_conversation_message'),
        ('myproject', '0003_userfile_status'),
    ]

    operations = [
    ]
